### ISSUE TITLE
RegEx modifiers aren't working

### ISSUE THREAD

**Issue by LawnCable** [luggage66/Sprache-js#4]
Example with the ignoreCase operator
```js
const regex = /[0-9a-fA-F]{2}/i
console.log("regex.ignoreCase", regex.ignoreCase) // regex.ignoreCase true
console.log(regex.test("7b"));

console.log(
    Parse.regex(regex).parse("7b") // throws an "not found error"
)
```
So the operator breaks something, because if it were simply ignored, I wouldn't get an error. (the solution would probably involve removing the modifiers from the original regex and then reapplying them the the newly build one in `Parser.regexMatch`)

**Comment by luggage66** [comment]
I see the problem. It's where it 'wraps' a regexp, here: https://github.com/luggage66/Sprache-js/blob/master/src/parse.ts#L625

Will fix it later today (dealing with the tests for it first).

**Comment by luggage66** [comment]
Fixed
